remote_theme: jekyll-theme-cayman
title: Clue Cell Images and Amsel Criteria Values with Bacterial Vaginosis Diagnostic Labels
description: Amsel Criteria Based Computer Vision for Diagnosing Bacterial Vaginosis Dataset
